<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subscription_grippy-host</name>
   <tag></tag>
   <elementGuidId>69dff943-d721-4def-b08e-78fb0c4eaacf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.grippy-host</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ins[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.grippy-host</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe2ea926-0212-44a5-9bef-f306605b171e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grippy-host</value>
      <webElementGuid>f469341e-337f-402c-b02e-c9aa71896abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/ins[@class=&quot;adsbygoogle adsbygoogle-noablate&quot;]/div[@class=&quot;grippy-host&quot;]</value>
      <webElementGuid>391021db-7333-4723-92fd-c87133a82ab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins[2]/div</value>
      <webElementGuid>6d1ce109-f9aa-491a-91ff-d38010ccd810</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
