<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>948b06e2-cd45-4e82-9d6f-1116ffc1bbda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='google-rewarded-video']/div/video</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>video</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>70aa70af-d015-40df-8b97-f30bddabdc5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://v.adsrvr.org/sg2o27m/cq8movx/rlkk7udu81/2szuw50q_5_9999.mp4</value>
      <webElementGuid>ebb593e0-9e98-445b-8018-1b562a0a0da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>2d46c011-f466-42ff-af8d-f708a95e266f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;google-rewarded-video&quot;)/div[1]/video[1]</value>
      <webElementGuid>2b122d39-8cd7-4b68-a002-401c8b11031b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_viewProduct/iframe_Close_ad_iframe</value>
      <webElementGuid>57a1fbf0-15e6-4dc0-9ebf-3b826587b8cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='google-rewarded-video']/div/video</value>
      <webElementGuid>a060f119-86b5-4654-ad65-2bbdd1c3f6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>56a1c2eb-e0dd-41f8-b5ac-f456e3fb30e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'https://v.adsrvr.org/sg2o27m/cq8movx/rlkk7udu81/2szuw50q_5_9999.mp4']</value>
      <webElementGuid>ec15fe23-38e6-45f7-9dc2-3b9dcd6ba11b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
