<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Regression_Checkout - Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>fe94de18-e1b6-43d1-aebb-68a594686526</testSuiteGuid>
   <testCaseLink>
      <guid>4e616669-8995-4952-901e-d89de8670bca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>'Herliana'</defaultValue>
         <description></description>
         <id>10865ec3-79fd-477e-8fd3-c2ef81cd1e49</id>
         <masked>false</masked>
         <name>nameonCard</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Scenarios/Scenario_ProductPurchase</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>68bc28e1-2d6b-4d97-aa7e-69d6b308d34a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data/productPurchaseData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>68bc28e1-2d6b-4d97-aa7e-69d6b308d34a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nameonCard</value>
         <variableId>10865ec3-79fd-477e-8fd3-c2ef81cd1e49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>68bc28e1-2d6b-4d97-aa7e-69d6b308d34a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cardNumber</value>
         <variableId>c81cc711-7c4c-480e-b159-9defcec9302e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>68bc28e1-2d6b-4d97-aa7e-69d6b308d34a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cvc</value>
         <variableId>a7c24732-4965-43d0-b9f8-2549cccda98e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>68bc28e1-2d6b-4d97-aa7e-69d6b308d34a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expiryMonth</value>
         <variableId>b888acef-673b-4725-b365-1623cc70e1ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>68bc28e1-2d6b-4d97-aa7e-69d6b308d34a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expiryYear</value>
         <variableId>cc47798a-253b-4f45-9cfa-a0b0fdd2d915</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
