<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subscription_grippy-host</name>
   <tag></tag>
   <elementGuidId>c4c7b0c3-8898-4515-8dfb-5ef09b5165c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ins[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.grippy-host</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.grippy-host</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f9c9667-bad4-408e-89a7-ac7fec758c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grippy-host</value>
      <webElementGuid>9a036cea-1d76-41c6-ab6b-51b9907df200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/ins[@class=&quot;adsbygoogle adsbygoogle-noablate&quot;]/div[@class=&quot;grippy-host&quot;]</value>
      <webElementGuid>e0e1b240-caa8-4d07-a0f1-86138ab985f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins[2]/div</value>
      <webElementGuid>6780be55-26ae-4976-8a59-5adbc320e946</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
