<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quantity_quantity</name>
   <tag></tag>
   <elementGuidId>5add545a-cf21-4f14-bd4b-35ec04dd56e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#quantity</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95c5a126-bf94-4fcb-ab20-7cf154920138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7469ac43-419c-49c9-a12f-ea79afc6e08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>c4943768-cee1-4e8e-8dfb-ed8e7f2d4976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>1bcd34fa-2990-44ee-9d70-890cfb0d55e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>05bd6aec-ab5c-443a-841a-b3fefd4f1784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6fc35e0f-62c6-4858-9feb-3975908ab392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity&quot;)</value>
      <webElementGuid>0486c4dc-f7da-42b1-8ad3-f822d2a364a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity']</value>
      <webElementGuid>4e9f0835-401a-455d-9abf-75896ffd0f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fe4157b1-e969-4edd-a4ad-46457f9d67f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'quantity' and @id = 'quantity']</value>
      <webElementGuid>0a150683-0b4c-4e41-bcdd-a35e269873bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
